### ISSUE TITLE
Removal of special comments in border

### ISSUE THREAD

**Issue by jorenvanhee** [ben-eb/postcss-discard-comments#18]
My special comments, if used with border, are getting removed.

Original:
```css
.buggy {
  color: #999 /*!theme-color*/;
  border: 1px solid #999 /*!theme-color*/;
  background-color: #999 /*!theme-color*/;
}
```

Minified:
```css
.buggy{color:#999 /*!theme-color*/;border:1px solid #999;background-color:#999 /*!theme-color*/}
```
