### ISSUE TITLE
Removed whitespace as a side-effect when no comment found

### ISSUE THREAD

**Issue by felixsanz** [ben-eb/postcss-discard-comments#44]
this plugin is converting this:

```css
.string {
  color: #2aa198;
}

.string.regexp {
  color: #dc322f;
}
```
Into this:
```css
.string{
  color:#2aa198;
}

.string.regexp{
  color:#dc322f;
}
```

So it's removing whitespace where it shouldn't. It should just remove comments if they are found, otherwise leave it as it is. What is now doing is some sort of minification as an unintended side-effect
