### ISSUE TITLE
Support for multiline comments

### ISSUE THREAD

**Issue by akoenig** [ben-eb/postcss-discard-comments#5]
Hey @ben-eb :)

first of all: thanks for the plugin :+1: 

This would not be an issue if I hadn't a question, right? :)

I'm observing a problem with multiline comments. I utilize `sass` for my CSS pre-processing and using `postcss` for several downstream actions. If i use multiline comments (which is necessary for generating a style guide with the help of [postcss-style-guide](https://github.com/morishitter/postcss-style-guide)) I see that my comments do not disappear in the results.

Any chance to add support for this use case?

**Comment by ben-eb** [comment]
What does the output look like?

**Comment by akoenig** [comment]
```css
/*

# Pagination

...

*/.pagination{display:-webkit-flex;display:-ms-flexbox;display:flex;list-style-type:none;margin:0;padding:0}.pagination__item{margin:0 6px}
```
